
name: 'starbucks_dw'
version: '1.0.0'

profile: 'starbucks_dw'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  starbucks_dw:
    staging:
      +schema: staging
    marts:
      +schema: marts
    reporting:
      +schema: reporting
      +enabled: true

seeds:
  +schema: raw
